version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@ruby
        name: build_ruby
        displayName: Ruby 构建
        # 支持2.5.9、2.6.8、2.7.4、3.0.2四个版本
        rubyVersion: 3.0.2
        # 构建命令
        commands:
          - set -ex
          - bundle install
          - chmod +x -R bin
          - bin/rails  webpacker:install
          - bin/rails db:migrate RAILS_ENV=test
          - bin/rails test
          - RAILS_ENV=production bin/rails assets:precompile
        # 非必填字段，开启后表示将构建产物暂存，但不会上传到制品库中，7天后自动清除
        artifacts:
            # 构建产物名字，作为产物的唯一标识可向下传递，支持自定义，默认为BUILD_ARTIFACT。在下游可以通过${BUILD_ARTIFACT}方式引用来获取构建物地址
          - name: BUILD_ARTIFACT
            # 构建产物获取路径，是指代码编译完毕之后构建物的所在路径
            path:
              - ./
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        # 上游构建任务定义的产物名，默认BUILD_ARTIFACT
        dependArtifact: BUILD_ARTIFACT
        # 上传到制品库时的制品命名，默认output
        artifactName: output
        dependsOn: build_ruby
triggers:
  pr:
    branches:
      include:
        - master
